services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: /bin/sh -c "alembic upgrade head && uvicorn api.index:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PGDATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/postgres
      - LOAD_TEST_DATA=true
    volumes:
      - ./api:/app/api
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts   
    depends_on:
      - db
    env_file:
      - .env
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: