FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat bash

# Install deps (cached layer)
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install

# Copy app code
COPY frontend .

EXPOSE 3000
CMD ["npm", "run", "dev"]
