# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY ./api/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code into /app/api/
COPY ./api ./api
COPY ./scripts ./scripts
COPY ./migrations ./migrations
COPY ./alembic.ini .
COPY ./start.sh .
RUN chmod +x start.sh

# Expose FastAPI default port
EXPOSE 8000

# Run FastAPI app with uvicorn
CMD ["./start.sh"]
