# Use official Node.js image
FROM node:20-bullseye

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY ./frontend .

# Accept build-time variable
ARG NEXT_PUBLIC_API_URL
# Persist it as environment variable for runtime
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Build Next.js app
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
