import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen px-4 py-8 max-w-3xl mx-auto justify-center items-center`}
      >
        <header className="sticky top-0 bg-white z-10 w-full">
          <h1
            className="text-center text-4xl font-extrabold tracking-tight text-balance py-4 bg-gradient-to-r from-slate-700 via-slate-400 to-slate-700 bg-clip-text text-transparent"
          >
            <Link href="/">Homework Wiki</Link>
          </h1>
        </header>

        {children}

        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
